# Generated by Django 4.1.2 on 2023-02-03 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='upload',
            new_name='upload_date',
        ),
    ]
